training_pipeline_config:
  pipeline_name: housing
  artifact_dir: artifact

data_ingestion_config:
  dataset_download_url: https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz
  raw_data_dir: raw_data
  tgz_download_dir: tgz_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test 

data_validation_config:
  schema_file_name: "schema.yaml"
  report_file_name: "report.json"
  report_page_file_name: "report.html"

data_transformation_config:
  add_bedroom_per_room : true
  transformed_dir : transformed_data
  transformed_train_dir : train
  transformed_test_dir : test
  preprocessed_dir :  preprocessed
  preprocessed_object : preprocessed.pkl



